### PR TITLE
Fix 0.36.0 compilation error

### PR DESCRIPTION
**Pull request by watzon**
The changed line doesn't compile in 0.36.0, and I'm surprised it compiled in 0.35.1

### CODE REVIEW

**Review by robacarp — APPROVED** [review]
thanks @watzon
